services:
  mongodb:
    image: mongo:7
    container_name: tp1-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:16
    container_name: tp1-postgres
    environment:
      POSTGRES_DB: reservationdb
      POSTGRES_USER: reservations
      POSTGRES_PASSWORD: reservations
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  postgres-data:
